service: serverless-espn-ffdata
app: serverless-espn-ffdata-app
org: lukethetechsplorer

provider:
  name: aws
  runtime: nodejs10.x

functions:
  hello:
    handler: handler.ping
    events:
      - http: GET ping
        cors: true
  leagueOverview:
    handler: handler.overview
    events:
      - http:
          path: leagues/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
              querystrings:
                season: false
  weeklyRosters:
    handler: handler.weeklyRosters
    events:
      - http:
          path: leagues/{id}/teams/{teamId}/roster
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
                teamId: true
              querystrings:
                season: false
                week: false
  currentMatchup:
    handler: handler.currentMatchup
    events:
      - http:
          path: leagues/{id}/teams/{teamId}/boxscore
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
                teamId: true
              querystrings:
                season: false
                week: false
  seasonStats:
    handler: handler.seasonStats
    events:
      - http:
          path: leagues/{id}/teams/season-stats
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
              querystrings:
                season: false